@startuml
skinparam classAttributeIconSize 0

' ==========================================
' SENSORES
' ==========================================

' ==INTERFACES==
package "sensores" <<Frame>> #DDDDDD{
  interface ISensor {
      + getIdentificador(): String
      + medir()
      + calibrar(offset: double)
      + estaCalibrado(): boolean
  }

  interface IUnidad {
      + getSimbolo(): String
  }

  ' ==CLASES==
  abstract class SensorMeteorologico {
      - id: String
      - offsetCalibracion: double
      - ultimaLectura: double
      - fechaUltimaLectura: LocalDateTime
      - fechaInstalacion: LocalDateTime
  }

  class SensorTemperatura {
      {static} - contador: int
      + cambiarUnidad(u: UnidadTemperatura)
  }

  class SensorHumedad {
      {static} - contador: int
  }

  class SensorPresionAtmosferica {
      {static} - contador: int
  }

  class Rango {
      - valorMinimo: double
      - valorMaximo: double
      + enRango(valor: double): boolean
  }


  ' ==ENUMERACIONES==
  enum UnidadTemperatura <<enumeration>> {
      CELSIUS
      FAHRENHEIT
      KELVIN
      --
      + getSimbolo(): String
  }

  enum UnidadHumedad <<enumeration>> {
      PORCENTAJE
      --
      + getSimbolo(): String
  }

  enum UnidadPresionAtmosferica <<enumeration>> {
      HECTOPASCALES
      PASCALES
      MILIBARES
      --
      + getSimbolo(): String
  }


}

' ==========================================
' PROCESAMIENTO
' ==========================================
package "procesamiento" <<Frame>> #DDDDDD {

'==INTERFACES== 
interface IConversor{
  + getUnidadOrigen(): IUnidad;
  + getUnidadDestino(): IUnidad;
  + convertir(valor: double): double;
}

'==CLASES== 
    class ProcesadorDatos {
        + registrarLectura(valor: double)
        + getMedia(): double
        + getMinimo(): double
        + getMaximo(): double
    }
    class Lectura {
        - valor: double
        - fechaHora: LocalDateTime
    }

    class ConversorIdentidad {
    }

    class ConversorTemperatura{
        - origen: UnidadTemperatura
        - destino: UnidadTemperatura
        + factorCelsiusKelvin(origen:UnidadTemperatura, destino:UnidadTemperatura): double 
        + factorKelfinFarenheit(origen:UnidadTemperatura, destino:UnidadTemperatura): double 
    }
    
    class ConversorPresion {
        - origen: UnidadPresionAtmosferica
        - destino: UnidadPresionAtmosferica
        + factor hPascalPascal(origen:UnidadPresion, destino:UnidadPresion): double 
        + factorPascalMilibar(origen:UnidadPresion, destino:UnidadPresion): double 
    }

}



' ==========================================
' METEREOLOGIA
' ==========================================
class EstacionMeteorologica {
    - nombre: String
    + addSensor(sensor: ISensor)
    + lanzarMedicion(fecha: LocalDateTime)
    + medicionPeriodica(horasIntervalo: double, lecturasMaximas: int)
    + getSensor(id: String): ISensor
    + getSensores(tipo: Class<?>): List<ISensor>
}

class Ubicacion {
    - latitud: double
    - longitud: double
}



' ==========================================
' ESTRATEGIAS
' ==========================================

package "estrategias" <<Frame>> #DDDDDD{
  interface IEstrategia{
    + generarValor(): double
  }

  class EstrategiaGeneracionEnRango {
    - minimo: double
    - maximo: double
    - probabilidadDesborde: double

  }

  class EstrategiaGeneracionSimilar {
    - porcentajeDesviacion: double

  }

  class EstrategiaGeneracionEnMedia{
    - porcentajeDesviacion: double

  }
}
' ==========================================
' RELACIONES
' ==========================================

' Implementaciones (Realization) -> Línea punteada con flecha hueca
ISensor <|.. SensorMeteorologico

IUnidad <|.. UnidadTemperatura
IUnidad <|.. UnidadHumedad
IUnidad <|.. UnidadPresionAtmosferica

IEstrategia <|.. EstrategiaGeneracionEnRango 
IEstrategia <|.. EstrategiaGeneracionSimilar
IEstrategia <|.. EstrategiaGeneracionEnMedia 

IConversor <|.. ConversorIdentidad
IConversor <|.. ConversorTemperatura
IConversor <|.. ConversorPresion 

' Herencia (Extension) --> Línea continua con flecha hueca
SensorMeteorologico <|-- SensorTemperatura
SensorMeteorologico <|-- SensorHumedad
SensorMeteorologico <|-- SensorPresionAtmosferica

' Agregación y Composición
EstacionMeteorologica o-- "*" ISensor : sensores: Map<String, ISensor>
EstacionMeteorologica *-- "1" Ubicacion : ubicacionGeografica

SensorMeteorologico *--  ProcesadorDatos : "procesador"

ProcesadorDatos *-- "*" Lectura: historial

' Asociaciones dirigidas
SensorMeteorologico -->  Rango : rangoValores
SensorMeteorologico -->  IUnidad : unidadDeLectura
SensorMeteorologico -up-> IEstrategia: estrategiaGeneracion

ProcesadorDatos -->  IConversor: conversor

@enduml
